[book]
title = "Veloren: An Owner's Manual"
authors = ["Joshua Barretto", "Marcel Märtens"]

[output.html]
default-theme = "dark"
additional-css = ["custom.css"]
git-repository-url = "https://gitlab.com/veloren/book"
git-repository-icon = "fa-gitlab"
